import type { Metadata } from 'next';
import { Work_Sans } from 'next/font/google';
import './globals.css';
import { ClerkProvider } from '@clerk/nextjs';
import { ThemeProvider } from 'next-themes';
import { Toaster } from 'sonner';
import Navbar from '@/frontend/navbar/Navbar';
import Profile from '@/frontend/home/Profile';

const work_Sans = Work_Sans({
	subsets: ['latin'],
});

export const metadata: Metadata = {
	title: 'social media app',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<ClerkProvider>
			<html
				lang='en'
				suppressHydrationWarning>
				<body className={`${work_Sans.className}`}>
					<ThemeProvider
						attribute='class'
						defaultTheme='dark'
						enableSystem
						disableTransitionOnChange>
						<div>
							<Navbar />
						</div>
						<main className='w-full p-8  grid grid-cols-1 lg:grid-cols-12 gap-6'>
							<div className='hidden lg:block lg:col-span-3'>
								<Profile />
							</div>
							<div className='lg:col-span-9'>{children}</div>
						</main>
						<Toaster />
					</ThemeProvider>
				</body>
			</html>
		</ClerkProvider>
	);
}